/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

/**
 *
 * @author HARUN AL RASYID
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPetani = new javax.swing.JButton();
        btnLahan = new javax.swing.JButton();
        btnPupuk = new javax.swing.JButton();
        btnProduksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PENDATAAN PERTANIAN");

        btnPetani.setText("PENDATAAN PETANI");
        btnPetani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetaniActionPerformed(evt);
            }
        });

        btnLahan.setText("PENDATAAN LAHAN");
        btnLahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLahanActionPerformed(evt);
            }
        });

        btnPupuk.setText("PENDATAAN PUPUK");
        btnPupuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPupukActionPerformed(evt);
            }
        });

        btnProduksi.setText("PENDATAAN PRODUKSI");
        btnProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProduksi)
                    .addComponent(btnLahan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPetani, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnPetani)
                .addGap(42, 42, 42)
                .addComponent(btnLahan)
                .addGap(41, 41, 41)
                .addComponent(btnPupuk)
                .addGap(38, 38, 38)
                .addComponent(btnProduksi)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPetaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetaniActionPerformed
        // TODO add your handling code here:
        framePetani framePetani = new framePetani();
        framePetani.setVisible(true);
    }//GEN-LAST:event_btnPetaniActionPerformed

    private void btnLahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLahanActionPerformed
        // TODO add your handling code here:
        frameLahan frameLahan = new frameLahan();
        frameLahan.setVisible(true);
    }//GEN-LAST:event_btnLahanActionPerformed

    private void btnPupukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPupukActionPerformed
        // TODO add your handling code here:
        framePupuk framePupuk = new framePupuk();
        framePupuk.setVisible(true);
    }//GEN-LAST:event_btnPupukActionPerformed

    private void btnProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduksiActionPerformed
        // TODO add your handling code here:
        frameProduksi frameProduksi = new frameProduksi();
        frameProduksi.setVisible(true);
    }//GEN-LAST:event_btnProduksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLahan;
    private javax.swing.JButton btnPetani;
    private javax.swing.JButton btnProduksi;
    private javax.swing.JButton btnPupuk;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
