/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import configdb.tbl_pupuk; 
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel; // Untuk mengisi JComboBox
import javax.swing.table.DefaultTableModel; // Untuk JTable
import javax.swing.event.ListSelectionListener; // Untuk interaksi klik JTable
import javax.swing.event.ListSelectionEvent;   // Untuk interaksi klik JTable
/**
 *
 * @author HARUN AL RASYID
 */
public class framePupuk extends javax.swing.JFrame {
    private tbl_pupuk objekPupuk;
    /**
     * Creates new form framePupuk
     */
    public framePupuk() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        objekPupuk = new tbl_pupuk(); // Inisialisasi DAO
        loadJenisPupuk(); // Panggil method untuk mengisi JComboBox
        tampilDataPupuk(); 
        
        // Listener JTable (Wajib untuk interaksi)
        tabelPupuk.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) { 
                    tabelPupukMouseClicked(); 
                }
            }
        });
    }
private void loadJenisPupuk() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("-- Pilih Jenis --"); 
        model.addElement("Anorganik"); 
        model.addElement("Organik"); 
        cmbJenisPupuk.setModel(model); 
    }    
// =========================================================
// METHOD TAMPIL DATA (READ)
// =========================================================
private void tampilDataPupuk() {
    // PERHATIAN: Tambahkan import javax.swing.table.DefaultTableModel di bagian atas file!
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pupuk");
    model.addColumn("Nama Pupuk");
    model.addColumn("Jenis"); 
    model.addColumn("Dosis (kg/ha)");

    try {
        java.sql.ResultSet rs = objekPupuk.getAllPupuk(); 
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pupuk"),
                rs.getString("nama_pupuk"),
                rs.getString("jenis_pupuk"),
                rs.getDouble("dosis_per_ha_kg") // Ambil sebagai Double
            });
        }
        tabelPupuk.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saat mengisi tabel: " + e.getMessage());
    }
}
// =========================================================
// METHOD UNTUK MENGISI FIELD SAAT BARIS DI TABEL DIKLIK
// =========================================================
private void tabelPupukMouseClicked() {
    int baris = tabelPupuk.getSelectedRow();
    if (baris != -1) { 
        // Mengisi fields dari JTable
        txtIdPupuk.setText(tabelPupuk.getValueAt(baris, 0).toString());
        txtNamaPupuk.setText(tabelPupuk.getValueAt(baris, 1).toString());
        
        // Mengisi JComboBox Jenis Pupuk (Index 2)
        cmbJenisPupuk.setSelectedItem(tabelPupuk.getValueAt(baris, 2).toString());
        
        txtDosis.setText(tabelPupuk.getValueAt(baris, 3).toString());
        
        // Kunci ID (PK)
        txtIdPupuk.setEnabled(false);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdPupuk = new javax.swing.JTextField();
        txtNamaPupuk = new javax.swing.JTextField();
        cmbJenisPupuk = new javax.swing.JComboBox<>();
        txtDosis = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPupuk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Pupuk");

        jLabel2.setText("Nama Pupuk");

        jLabel3.setText("Jenis Pupuk");

        jLabel4.setText("Dosis Per (kg)");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tabelPupuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pupuk", "Nama Pupuk", "Jenis Pupuk", "Dosis Per (kg)"
            }
        ));
        jScrollPane1.setViewportView(tabelPupuk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdPupuk)
                    .addComponent(txtNamaPupuk)
                    .addComponent(cmbJenisPupuk, 0, 107, Short.MAX_VALUE)
                    .addComponent(txtDosis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbJenisPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String id = txtIdPupuk.getText();
    String nama = txtNamaPupuk.getText();
    String jenis = cmbJenisPupuk.getSelectedItem().toString();
    
    double dosis = 0.0;
    try {
        dosis = Double.parseDouble(txtDosis.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Dosis harus berupa angka!");
        return;
    }

    if (id.isEmpty() || nama.isEmpty() || jenis.equals("-- Pilih Jenis --")) {
        JOptionPane.showMessageDialog(this, "ID, Nama, dan Jenis wajib diisi!");
        return;
    }
    
    objekPupuk.SimpanAnggota(id, nama, jenis, dosis);
    
    // REFRESH TABEL DAN BUKA KUNCI
    tampilDataPupuk(); 
    txtIdPupuk.setEnabled(true);
    
    // Kosongkan fields
    txtIdPupuk.setText("");
    txtNamaPupuk.setText("");
    txtDosis.setText("");
    cmbJenisPupuk.setSelectedIndex(0);

    
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        String id = txtIdPupuk.getText();
    String nama = txtNamaPupuk.getText();
    String jenis = cmbJenisPupuk.getSelectedItem().toString();
    
    double dosis = 0.0;
    try {
        dosis = Double.parseDouble(txtDosis.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Dosis harus berupa angka!");
        return;
    }
    
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan ID Pupuk yang akan diubah!");
        return;
    }
    
    objekPupuk.ubahAnggota(id, nama, jenis, dosis);
    
    // REFRESH TABEL DAN BUKA KUNCI
    tampilDataPupuk();
    txtIdPupuk.setEnabled(true);
    
    // Opsional: Bersihkan fields
    txtIdPupuk.setText("");
    
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String id = txtIdPupuk.getText();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan ID Pupuk yang akan dihapus!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus data ID " + id + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == JOptionPane.YES_OPTION) {
         objekPupuk.hapusAnggota(id);
         
         // REFRESH TABEL DAN BUKA KUNCI
         tampilDataPupuk();
         txtIdPupuk.setEnabled(true);
         
         // Kosongkan fields
         txtIdPupuk.setText("");
         txtNamaPupuk.setText("");
         txtDosis.setText("");
         cmbJenisPupuk.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePupuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbJenisPupuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPupuk;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtIdPupuk;
    private javax.swing.JTextField txtNamaPupuk;
    // End of variables declaration//GEN-END:variables
}
