/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import configdb.tbl_petani;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionListener; 
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author HARUN AL RASYID
 */
public class framePetani extends javax.swing.JFrame {
    
   private tbl_petani tblpetani;
    /**
     * Creates new form framePetani
     */
    public framePetani() {
        initComponents();
        this.setLocationRelativeTo(null);
        tblpetani = new tbl_petani();
        
        
        
    }
    private void tabelPetaniMouseClicked() {
    int baris = tabelPetani.getSelectedRow();
    // Pastikan ada baris yang terpilih
    if (baris != -1) { 
        // Mengisi fields dari JTable
        txtIdPetani.setText(tabelPetani.getValueAt(baris, 0).toString());
        txtNamaPetani.setText(tabelPetani.getValueAt(baris, 1).toString());
        txtAlamat.setText(tabelPetani.getValueAt(baris, 2).toString());
        txtNoHp.setText(tabelPetani.getValueAt(baris, 3).toString());
        
        // Kunci ID agar tidak diubah saat proses UPDATE
        txtIdPetani.setEnabled(false);
    }
}
    private void tampilDataPetani() {
    // Definisikan Model untuk JTable
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Petani");
    model.addColumn("Nama");
    model.addColumn("Alamat");
    model.addColumn("No. HP");

    try {
        // Ambil data dari DAO
        java.sql.ResultSet rs = tblpetani.getAllPetani(); 
        
        // Isi Model dengan data
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_petani"),
                rs.getString("nama_petani"),
                rs.getString("alamat"),
                rs.getString("no_hp")
            });
        }
        
        // Set Model ke JTable
        tabelPetani.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saat mengisi tabel: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdPetani = new javax.swing.JTextField();
        txtNamaPetani = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPetani = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Petani");

        jLabel2.setText("Nama Petani");

        jLabel3.setText("Alamat");

        jLabel4.setText("NO.Hp");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tabelPetani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Petani", "Nama Petani", "Alamat", "NO.Hp"
            }
        ));
        jScrollPane1.setViewportView(tabelPetani);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdPetani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNamaPetani, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdPetani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaPetani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    try {
        if (txtIdPetani.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID Petani Belum Diisi");
            txtIdPetani.requestFocus();
        } else if (txtNamaPetani.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Petani Belum Diisi");
            txtNamaPetani.requestFocus();
        } else if (txtAlamat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
        } else if (txtNoHp.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No Hp Belum Diisi");
        
        } else {
            // 🔹 Tambahkan log agar tahu event dijalankan
            System.out.println("Tombol Tambah Ditekan");

            // 🔹 Panggil fungsi simpan (tidak ubah strukturnya)
            tblpetani.SimpanAnggota(
                txtIdPetani.getText(),
                txtNamaPetani.getText(),
                txtAlamat.getText(),
                txtNoHp.getText()
            );

            // 🔹 Tambahkan indikator berhasil
            if (tblpetani.validasi == true){
                JOptionPane.showMessageDialog(null, "ID sudah terdaftar! Data tidak disimpan.");
                txtNamaPetani.setText(tblpetani.VAR_nama);
                txtAlamat.setText(tblpetani.VAR_alamat);
                txtNoHp.setText(tblpetani.VAR_nohp);
                
            } else {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan ke database!");
                tampilDataPetani(); // <-- REFRESH TABEL
    // Bersihkan fields dan buka kunci ID
    txtIdPetani.setText(null);
    txtNamaPetani.setText(null);
    txtAlamat.setText(null);
    txtNoHp.setText(null);
    txtIdPetani.setEnabled(true);

            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace(); // tampilkan detail di console
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            tblpetani.ubahAnggota(txtIdPetani.getText(), txtNamaPetani.getText(), txtAlamat.getText(), txtNoHp.getText());
            tampilDataPetani(); // <-- REFRESH TABEL
            txtIdPetani.setEnabled(true);
                   
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    String id = txtIdPetani.getText(); // Ambil ID dari field
    
    // [1] Validasi Input
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel untuk dihapus!");
        return;
    }
    
    // [2] Konfirmasi Penghapusan (Wajib sebelum menghapus data)
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus data ID " + id + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            // [3] Panggil DAO DELETE
            tblpetani.hapusAnggota(id);
            
            // [4] REFRESH JTABLE
            tampilDataPetani(); 
            
            // [5] BERSIHKAN FIELDS dan BUKA KUNCI ID
            txtIdPetani.setText(null);
            txtNamaPetani.setText(null);
            txtAlamat.setText(null);
            txtNoHp.setText(null);
            txtIdPetani.setEnabled(true); // Membuka kunci ID setelah hapus
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat hapus: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePetani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPetani;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIdPetani;
    private javax.swing.JTextField txtNamaPetani;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables

    
}
